export const API_PRODUCTS_SUCCESS = "API_PRODUCTS_SUCCESS";
export const API_PRODUCTS_REQUEST = "API_PRODUCTS_REQUEST"
export const API_PRODUCTS_ERROR = "API_PRODUCTS_ERROR"
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
